### GET hello
GET http://localhost:8888/hello


### GET gw
GET http://localhost:8888/gw


### GET ga
GET http://localhost:8888/gw

### 获取用户信息
POST http://localhost:8888/gw/ubrpc/io.unbong.ubrpc.demo.api.UserService
Content-Type: application/json

{
  "service": "io.unbong.ubrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}